-- Migration: Create partner_invites table
-- Purpose: Store invite tokens for partner registration
-- Called by Website Booking when admin approves a partner application

CREATE TABLE IF NOT EXISTS partner_invites (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    token VARCHAR(64) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    partner_name VARCHAR(255),
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'used', 'expired')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    used_at TIMESTAMPTZ
);

-- Create index on token for fast lookups
CREATE INDEX IF NOT EXISTS idx_partner_invites_token ON partner_invites(token);

-- Create index on status for querying pending invites
CREATE INDEX IF NOT EXISTS idx_partner_invites_status ON partner_invites(status);

-- RLS: Only service role can access this table (via API v1 with JWT)
ALTER TABLE partner_invites ENABLE ROW LEVEL SECURITY;

-- No public access policy - only accessible via service role or admin
-- The API endpoints will use supabaseAdmin client which bypasses RLS

COMMENT ON TABLE partner_invites IS 'Stores invite tokens for partner registration. Tokens are generated by Website Booking admin approval flow.';
COMMENT ON COLUMN partner_invites.token IS 'Unique token used in invite URL query parameter';
COMMENT ON COLUMN partner_invites.status IS 'pending = awaiting use, used = partner registered, expired = token expired';
COMMENT ON COLUMN partner_invites.expires_at IS 'Token expiration timestamp (default 7 days from creation)';
