ALTER TABLE public.transaction_items 
ADD COLUMN IF NOT EXISTS reference_id TEXT,
ADD COLUMN IF NOT EXISTS type TEXT,
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;

ALTER TABLE public.transaction_items 
ADD COLUMN IF NOT EXISTS price DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12, 2) DEFAULT 0;